inherit:
    - ../base.yaml

training:
    task_name: noisy_linear_regression
    curriculum:
        points:
            start: 31
            end: 45
            inc: 1

out_dir: ./results2/noisy_LR_baseline
debug_mode: False