inherit:
    - ../base.yaml

training:
    task_name: decision_tree
    curriculum:
        points:
            start: 87
            end: 101
            inc: 1

out_dir: ./results2/decision_tree_baseline
debug_mode: False