inherit:
    - ../base.yaml

model:
    pred_type: classification

training:
    curriculum:
        points:
            start: 31
            end: 45
            inc: 1

out_dir: ./results2/openml_baseline
debug_mode: False